module.exports = {
  User: require('./User'),
  Address: require('./Address'),
  Restaurant: require('./Restaurant'),
  FoodCategory: require('./FoodCategory'),
  FoodItem: require('./FoodItem'),
  Cart: require('./Cart'),
  Order: require('./Order'),
  Review: require('./Review'),
  Coupon: require('./Coupon'),
  CouponUsage: require('./CouponUsage'),
  Favorite: require('./Favorite'),
  Payment: require('./Payment'),
  Refund: require('./Refund'),
  Counter: require('./Counter'),
  DeliveryPartner: require('./DeliveryPartner'),
  DeliveryAssignment: require('./DeliveryAssignment'),
};
