const express = require('express');
const { query, param } = require('express-validator');
const geoController = require('../controllers/geo.controller');
const validate = require('../middleware/validate');
const { geoLimiter } = require('../middleware/rateLimiter');
const { authenticateUser } = require('../middleware/auth.middleware');

const router = express.Router();

// Public on purpose — guests choose a delivery location before they ever log in — so the
// per-IP rate limit is what protects the Google quota (autocomplete fires per keystroke,
// which is why the frontend debounces it).
router.use(geoLimiter);

const sessionToken = query('sessionToken')
  .optional()
  .matches(/^[A-Za-z0-9-]{8,64}$/)
  .withMessage('Invalid session token');

/**
 * @swagger
 * /geo/autocomplete:
 *   get:
 *     summary: Address suggestions for what the user is typing (Google Places, proxied)
 *     description: >
 *       Public and rate-limited. The Google API key stays on the server. Restricted to the country in GEO_COUNTRY
 *       (default `in`). Returns 503 when GOOGLE_MAPS_API_KEY is not configured. Pass the same `sessionToken` (any
 *       random 8–64 char string, generated by the client per search) to the autocomplete calls and the final
 *       /geo/place call so Google bills them as one session.
 *     tags: [Location]
 *     security: []
 *     parameters:
 *       - { in: query, name: q, required: true, schema: { type: string, minLength: 3, maxLength: 100 } }
 *       - { in: query, name: sessionToken, schema: { type: string } }
 *     responses:
 *       200: { description: 'Up to 6 suggestions, each with placeId, description, mainText and secondaryText' }
 *       422: { $ref: '#/components/responses/ValidationError' }
 *       429: { description: Too many requests }
 *       502: { description: Google unavailable }
 *       503: { description: Not configured, or Google quota exhausted }
 */
router.get(
  '/autocomplete',
  [query('q').trim().isLength({ min: 3, max: 100 }).withMessage('Type at least 3 characters'), sessionToken],
  validate,
  geoController.autocomplete
);

/**
 * @swagger
 * /geo/place/{placeId}:
 *   get:
 *     summary: Resolve a chosen suggestion into an address with coordinates
 *     tags: [Location]
 *     security: []
 *     parameters:
 *       - { in: path, name: placeId, required: true, schema: { type: string } }
 *       - { in: query, name: sessionToken, schema: { type: string } }
 *     responses:
 *       200: { description: "place: {placeId, name, formattedAddress, latitude, longitude, area, city, state, pincode}" }
 *       404: { description: Unknown place }
 *       503: { description: Not configured }
 */
router.get(
  '/place/:placeId',
  [param('placeId').matches(/^[A-Za-z0-9_-]{10,300}$/).withMessage('Invalid place id'), sessionToken],
  validate,
  geoController.place
);

/**
 * @swagger
 * /geo/reverse:
 *   get:
 *     summary: Turn GPS coordinates into an address (Google Geocoding, proxied)
 *     tags: [Location]
 *     security: []
 *     parameters:
 *       - { in: query, name: lat, required: true, schema: { type: number, minimum: -90, maximum: 90 } }
 *       - { in: query, name: lng, required: true, schema: { type: number, minimum: -180, maximum: 180 } }
 *     responses:
 *       200: { description: "place: {formattedAddress, latitude, longitude, area, city, state, pincode}" }
 *       404: { description: No address for that point }
 *       503: { description: Not configured }
 */
router.get(
  '/reverse',
  [
    query('lat').isFloat({ min: -90, max: 90 }).withMessage('lat must be between -90 and 90'),
    query('lng').isFloat({ min: -180, max: 180 }).withMessage('lng must be between -180 and 180'),
  ],
  validate,
  geoController.reverse
);

/**
 * @swagger
 * /geo/static-map:
 *   get:
 *     summary: A small static map image centered on a point, with one marker (M8 delivery tracking)
 *     description: >
 *       Authenticated (unlike the other /geo endpoints — this one returns actual image bytes and
 *       is heavier, so it isn't left fully public). Proxied through the backend so the Google key
 *       never reaches the browser. Returns 503 when GOOGLE_MAPS_API_KEY is not configured — the
 *       frontend shows a "map unavailable" state rather than anything fake.
 *     tags: [Location]
 *     parameters:
 *       - { in: query, name: lat, required: true, schema: { type: number, minimum: -90, maximum: 90 } }
 *       - { in: query, name: lng, required: true, schema: { type: number, minimum: -180, maximum: 180 } }
 *       - { in: query, name: zoom, schema: { type: integer, minimum: 1, maximum: 20, default: 15 } }
 *       - { in: query, name: width, schema: { type: integer, minimum: 100, maximum: 640, default: 400 } }
 *       - { in: query, name: height, schema: { type: integer, minimum: 100, maximum: 640, default: 250 } }
 *     responses:
 *       200: { description: PNG image, content: { image/png: { schema: { type: string, format: binary } } } }
 *       401: { $ref: '#/components/responses/Unauthorized' }
 *       422: { $ref: '#/components/responses/ValidationError' }
 *       502: { description: Google unavailable }
 *       503: { description: Not configured }
 */
router.get(
  '/static-map',
  authenticateUser,
  [
    query('lat').isFloat({ min: -90, max: 90 }).withMessage('lat must be between -90 and 90'),
    query('lng').isFloat({ min: -180, max: 180 }).withMessage('lng must be between -180 and 180'),
    query('zoom').optional().isInt({ min: 1, max: 20 }),
    query('width').optional().isInt({ min: 100, max: 640 }),
    query('height').optional().isInt({ min: 100, max: 640 }),
  ],
  validate,
  geoController.staticMap
);

module.exports = router;
